const snarkjs = require("snarkjs");
const fs = require("fs");
const path = require("path");

/**
 * Verify a zk-SNARK proof for the age_check circuit.
 * @param {Object} proof - The cryptographic proof generated by the holder
 * @param {Array} publicSignals - The public inputs/outputs of the circuit (e.g., threshold)
 * @returns {Promise<boolean>} True if valid, false otherwise.
 */
async function verifyAgeProof(proof, publicSignals) {
    const vKeyPath = path.resolve(__dirname, "../../zk-factory/build/vk_01.json");
    const vKey = JSON.parse(fs.readFileSync(vKeyPath, "utf-8"));

    try {
        const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);
        return isValid;
    } catch (error) {
        console.error("Proof verification failed:", error);
        return false;
    }
}

module.exports = {
    verifyAgeProof
};
