const snarkjs = require("snarkjs");
const fs = require("fs");
const path = require("path");

/**
 * Verify a zk-SNARK proof for the age_check circuit.
 * @param {Object} proof - The cryptographic proof generated by the holder
 * @param {Array} publicSignals - The public inputs/outputs of the circuit
 *   publicSignals[0] = isEligible (must be "1")
 *   publicSignals[1] = ageThreshold (must match the requested threshold)
 * @param {number} [expectedThreshold] - Optional: the threshold the verifier requested
 * @returns {Promise<{valid: boolean, reason?: string}>}
 */
async function verifyAgeProof(proof, publicSignals, expectedThreshold) {
    const vKeyPath = path.resolve(__dirname, "../../zk-factory/build/vk_01.json");
    const vKey = JSON.parse(fs.readFileSync(vKeyPath, "utf-8"));

    try {
        // 1️⃣ Cryptographic verification — checks the proof is mathematically valid
        const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);

        if (!isValid) {
            return { valid: false, reason: "Cryptographic proof verification failed" };
        }

        // 2️⃣ Semantic validation — check publicSignals values
        // publicSignals[0] = isEligible output from the circuit
        const isEligible = publicSignals[0];
        if (isEligible !== "1") {
            return { valid: false, reason: `isEligible signal is ${isEligible}, expected 1` };
        }

        // publicSignals[1] = ageThreshold (public input)
        // Verify it matches the threshold the verifier actually requested
        if (expectedThreshold !== undefined && expectedThreshold !== null) {
            const provenThreshold = parseInt(publicSignals[1]);
            if (provenThreshold !== parseInt(expectedThreshold)) {
                return {
                    valid: false,
                    reason: `Threshold mismatch: proof was for threshold=${provenThreshold} but verifier requested ${expectedThreshold}`
                };
            }
        }

        return { valid: true };

    } catch (error) {
        console.error("Proof verification failed:", error);
        return { valid: false, reason: error.message };
    }
}

module.exports = {
    verifyAgeProof
};
